"""create_identity_tables

Revision ID: c2d181442f64
Revises:
Create Date: 2026-09-10 11:37:22.399188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2d181442f64'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('identity_provider_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_identity_customers_email', 'identity_customers', ['email'], unique=True)
    op.create_index('idx_identity_customers_identity_provider_id', 'identity_customers', ['identity_provider_id'], unique=True)
    op.create_table('identity_customer_addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['identity_customers.id'], name='fk_identity_customer_addresses_customer_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'label', name='uq_identity_customer_addresses_customer_id_label')
    )
    op.create_table('identity_customer_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['identity_customers.id'], name='fk_identity_customer_preferences_customer_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'key', name='uq_identity_customer_preferences_customer_id_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('identity_customer_preferences')
    op.drop_table('identity_customer_addresses')
    op.drop_index('idx_identity_customers_identity_provider_id', table_name='identity_customers')
    op.drop_index('idx_identity_customers_email', table_name='identity_customers')
    op.drop_table('identity_customers')
    # ### end Alembic commands ###
