"""add discount and tax columns to cart items

Revision ID: af93d70c3076
Revises: 6b9bc53f22bf
Create Date: 2026-09-22 15:00:15.091032


"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af93d70c3076'
down_revision: Union[str, Sequence[str], None] = '6b9bc53f22bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
