"""create inventory tables

Revision ID: 4eb2d6781d50
Revises: 
Create Date: 2026-09-23 13:30:12.398759


"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb2d6781d50'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('quantity_reserved', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_on_hand >= 0', name='ck_inventory_items_non_negative_on_hand'),
    sa.CheckConstraint('quantity_reserved >= 0', name='ck_inventory_items_non_negative_reserved'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id', name='uq_inventory_items_variant_id')
    )
    op.create_index('idx_inventory_items_variant_id', 'inventory_items', ['variant_id'], unique=True)
    op.create_table('inventory_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('adjustment', 'reservation', 'release', 'confirmation')", name='ck_inventory_movements_kind'),
    sa.CheckConstraint('delta != 0', name='ck_inventory_movements_non_zero_delta'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], name='fk_inventory_movements_item_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inventory_movements_item_id', 'inventory_movements', ['inventory_item_id'], unique=False)
    op.create_index('idx_inventory_movements_reference_id', 'inventory_movements', ['reference_id'], unique=False)
    op.create_table('inventory_reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('reserved', 'confirmed', 'released')", name='ck_inventory_reservations_status'),
    sa.CheckConstraint('quantity > 0', name='ck_inventory_reservations_positive_quantity'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], name='fk_inventory_reservations_item_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_item_id', 'order_id', name='uq_inventory_reservations_item_order')
    )
    op.create_index('idx_inventory_reservations_item_id', 'inventory_reservations', ['inventory_item_id'], unique=False)
    op.create_index('idx_inventory_reservations_order_id', 'inventory_reservations', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_inventory_reservations_order_id', table_name='inventory_reservations')
    op.drop_index('idx_inventory_reservations_item_id', table_name='inventory_reservations')
    op.drop_table('inventory_reservations')
    op.drop_index('idx_inventory_movements_reference_id', table_name='inventory_movements')
    op.drop_index('idx_inventory_movements_item_id', table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index('idx_inventory_items_variant_id', table_name='inventory_items')
    op.drop_table('inventory_items')
    # ### end Alembic commands ###
