"""create catalog tables

Revision ID: 948b5adbd638
Revises: 
Create Date: 2026-09-14 11:40:27.206675


"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '948b5adbd638'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_brands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_catalog_brands_name')
    )
    op.create_table('catalog_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['catalog_categories.id'], name='fk_catalog_categories_parent_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_catalog_categories_parent_id', 'catalog_categories', ['parent_id'], unique=False)
    op.create_index('uq_catalog_categories_parent_id_name', 'catalog_categories', [sa.literal_column('lower(name)'), 'parent_id'], unique=True, postgresql_where=sa.text('parent_id IS NOT NULL'))
    op.create_index('uq_catalog_categories_root_name', 'catalog_categories', [sa.literal_column('lower(name)')], unique=True, postgresql_where=sa.text('parent_id IS NULL'))
    op.create_table('catalog_category_attributes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['catalog_categories.id'], name='fk_catalog_category_attributes_category_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'key', name='uq_catalog_category_attributes_category_id_key')
    )
    op.create_table('catalog_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('specs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['catalog_brands.id'], name='fk_catalog_products_brand_id'),
    sa.ForeignKeyConstraint(['category_id'], ['catalog_categories.id'], name='fk_catalog_products_category_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku', name='uq_catalog_products_sku')
    )
    op.create_index('idx_catalog_products_brand_id', 'catalog_products', ['brand_id'], unique=False)
    op.create_index('idx_catalog_products_category_id', 'catalog_products', ['category_id'], unique=False)
    op.create_table('catalog_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_products.id'], name='fk_catalog_variants_product_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku', name='uq_catalog_variants_sku')
    )
    op.create_index('idx_catalog_variants_product_id', 'catalog_variants', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_catalog_variants_product_id', table_name='catalog_variants')
    op.drop_table('catalog_variants')
    op.drop_index('idx_catalog_products_category_id', table_name='catalog_products')
    op.drop_index('idx_catalog_products_brand_id', table_name='catalog_products')
    op.drop_table('catalog_products')
    op.drop_table('catalog_category_attributes')
    op.drop_index('uq_catalog_categories_root_name', table_name='catalog_categories', postgresql_where=sa.text('parent_id IS NULL'))
    op.drop_index('uq_catalog_categories_parent_id_name', table_name='catalog_categories', postgresql_where=sa.text('parent_id IS NOT NULL'))
    op.drop_index('idx_catalog_categories_parent_id', table_name='catalog_categories')
    op.drop_table('catalog_categories')
    op.drop_table('catalog_brands')
    # ### end Alembic commands ###
